# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: grafana-datasources
#   namespace: monitoring
# data:
#   prometheus.yaml: |-
#     {
#         "apiVersion": 1,
#         "datasources": [
#             {
#                 "access": "proxy",
#                 "editable": true,
#                 "name": "prometheus",
#                 "orgId": 1,
#                 "type": "prometheus",
#                 "url": "http://prometheus-service.monitoring.svc:8080",
#                 "version": 1
#             }
#         ]
#     }
#   loki.yaml: |-
#     {
#         "apiVersion": 1,
#         "datasources": [
#             {
#                 "name": "Loki",
#                 "type": "loki",
#                 "uid": "loki",
#                 "access": "proxy",
#                 "url": "http://loki.monitoring:3100",
#                 "jsonData": {
#                     "httpMethod": "GET",
#                     "maxLines": 1000,
#                     "derivedFields": [
#                         {
#                             "datasourceUid": "tempo",
#                             "matcherRegex": "traceId=(\\w*)",
#                             "name": "traceId",
#                             "url": "${__value.raw}"
#                         }
#                     ]
#                 }
#             }
#         ]
#     }
#   tempo.yaml: |-
#     {
#         "apiVersion": 1,
#         "datasources": [
#             {
#                 "name": "Tempo",
#                 "type": "tempo",
#                 "uid": "tempo",
#                 "access": "proxy",
#                 "url": "http://tempo.monitoring.svc.cluster.local:3100",
#                 "jsonData": {
#                     "httpMethod": "GET",
#                     "tracesToLogsV2": {
#                         "datasourceUid": "loki"
#                     },
#                     "serviceMap": {
#                         "datasourceUid": "prometheus"
#                     },
#                     "nodeGraph": {
#                         "enabled": true
#                     },
#                     "search": {
#                         "hide": false
#                     },
#                     "lokiSearch": {
#                         "datasourceUid": "loki"
#                     }
#                 }
#             }
#         ]
#     }
