enabled: true
mode: "deployment"
config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  processors:
    batch: 
      timeout: 10s
      send_batch_size: 1024

    # resources:
    #   requests:
    #     cpu: 150m
    #     memory: 256Mi
    #   limits:
    #     cpu: 500m
    #     memory: 512Mi

  exporters:
    otlphttp:
      endpoint: http://tempo.monitoring.svc.cluster.local:4318
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlphttp]

image:
  repository: "otel/opentelemetry-collector-k8s"