loki-stack:
  fluent-bit:
    enabled: true

  loki:
    enabled: true
    isDefault: false
    url: http://loki.monitoring.svc.cluster.local:3100

    test:
      enabled: false

    monitoring:
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false

    auth_enabled: false

    server:
      http_listen_port: 3100

    common:
      ring:
        instance_addr: 0.0.0.0
        kvstore:
          store: inmemory
      replication_factor: 1
      path_prefix: /loki

    schema_config:
      configs:
        - from: 2020-05-15
          store: tsdb
          object_store: gcs
          schema: v13
          index:
            prefix: index_
            period: 24h

    storage_config:
      tsdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/index_cache
      gcs:
        bucket_name: logs-by-loki

tempo:
  metricsGenerator:
    enabled: true
    remoteWriteUrl: "http://prometheus.monitoring.svc.cluster.local:9090"
    
    storage:
      trace_id_batch_size: 100
      trace_id_expiration: 168h
      max_traces: 100000
      backend: gcs
      gcs:
        bucket_name: traces-by-tempo
        prefix: /tempo
        chunk_buffer_size: 10000000
        insecure: false

