apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nginx-ingress
  namespace:  monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/websocket-services: {{ .Release.Name }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2

spec:
  rules:
  - host: chatbot.monitoring.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 3000
