apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nginx-ingress
  namespace:  model-serving
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/websocket-services: {{ .Release.Name }}

spec:
  rules:
  - host: chatbot.custom.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 8051
