# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: chatbot-pv
# spec:
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: standard-rwo
#   hostPath:
#     path: /mnt/data