# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: chatbot-pvc
#   namespace: model-serving
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
#   storageClassName: standard-rwo