apiVersion: v1
kind: Pod
metadata:
  name: chatbot-pod
  namespace: model-serving
spec:
  containers:
  - name: chatbot-container
    image: nginx:latest
    volumeMounts:
    - mountPath: "/app/data"
      name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: chatbot-pvc